dutils.conf.urls = {
  code_browser: "/projects/<project_id>/browser/<slug>/browser/<path>",
  commit_detail: "/projects/<project_id>/browser/<slug>/commit/<commit_id>/",
  company: "/invoices/company/",
  contract_add: "/invoices/contract/<object_id>/",
  contract_index: "/invoices/contract/",
  dashboard: "/newsletter/dashboard/",
  dashboard_ajax: "/newsletter/get_dashboard/",
  display_meta: "/newsletter/display_meta/",
  "django-admindocs-bookmarklets": "/admin/doc/bookmarklets/",
  "django-admindocs-docroot": "/admin/doc/",
  "django-admindocs-filters": "/admin/doc/filters/",
  "django-admindocs-models-detail":
    "/admin/doc/models/<app_label>.<model_name>/",
  "django-admindocs-models-index": "/admin/doc/models/",
  "django-admindocs-tags": "/admin/doc/tags/",
  "django-admindocs-templates": "/admin/doc/templates/<template>/",
  "django-admindocs-views-detail": "/admin/doc/views/<view>/",
  "django-admindocs-views-index": "/admin/doc/views/",
  download_document: "/invoices/receipt/download_document/<object_id>/",
  group_create: "/newsletter/group/add/",
  group_delete: "/newsletter/group/delete/<object_id>/",
  group_list: "/newsletter/group/list/",
  group_update: "/newsletter/group/update/<object_id>/",
  home: "/",
  host: "/newsletter/host",
  invoices_index: "/invoices/",
  issue_add: "/projects/<project_id>/issue/save/",
  issue_delete: "/projects/<project_id>/issue/delete/<issue_id>/",
  issue_edit: "/projects/<project_id>/issue/save/<issue_id>/",
  issue_index: "/projects/<project_id>/issue/",
  link_count: "/newsletter/news/<link_hash>/",
  links_ajax: "/newsletter/get_links/",
  membership_add: "/projects/<project_id>/people/add/",
  membership_change: "/projects/<project_id>/people/change/<member_id>/",
  message_add: "/projects/<project_id>/message/save/",
  message_details: "/projects/<project_id>/message/details/<message_id>/",
  message_index: "/projects/<project_id>/message/",
  milestone_index: "/projects/<project_id>/milestone/",
  newsletter_add: "/newsletter/add/",
  newsletter_analytics: "/newsletter/analytics/<newsletter_id>/",
  newsletter_content: "/newsletter/content/<newsletter_id>/",
  newsletter_delete: "/newsletter/delete/<object_id>/",
  newsletter_edit: "/newsletter/edit/<newsletter_id>/",
  newsletter_index: "/newsletter/",
};
